In [1]:
import numpy as np

arr_1d = np.arange(1, 11)
arr_2d = np.arange(1, 10).reshape(3, 3)
arr_3d = np.random.rand(3, 5, 3)

def display_info(name, array):
    print(f"{name}:")
    print("Array:\n", array)
    print("Shape:", array.shape)
    print("Size:", array.size)
    print("Data type:", array.dtype)
    print("-" * 40)

display_info("1D Array", arr_1d)
display_info("2D Array", arr_2d)
display_info("3D Array", arr_3d)


1D Array:
Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int32
----------------------------------------
2D Array:
Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int32
----------------------------------------
3D Array:
Array:
 [[[0.68617729 0.8452028  0.88858509]
  [0.1827555  0.06303679 0.91179017]
  [0.68354758 0.1280398  0.12488385]
  [0.09639287 0.07928667 0.75637308]
  [0.87389033 0.74946216 0.34674167]]

 [[0.17592821 0.85805797 0.52286576]
  [0.59453522 0.45753344 0.87290054]
  [0.10160898 0.35926369 0.03874932]
  [0.27586937 0.74833165 0.94840922]
  [0.68975659 0.32094627 0.39738765]]

 [[0.17067416 0.33550984 0.1244142 ]
  [0.95044747 0.61174291 0.49575838]
  [0.69641007 0.36965482 0.27367106]
  [0.53492443 0.46894732 0.12346105]
  [0.06308407 0.50650838 0.29742145]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64
----------------------------------------


In [3]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

first_three = data[:3]
alternate = data[::2]
reversed_array = data[::-1]

print("First three:", first_three)
print("Alternate elements:", alternate)
print("Reversed array:", reversed_array)


First three: [10 20 30]
Alternate elements: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


In [5]:
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

add = A + B
subtract = A - B
multiply = A * B
divide = A / B
dot_product = np.dot(A, B)

mean_A = np.mean(A)
median_A = np.median(A)
std_A = np.std(A)
var_A = np.var(A)

max_B = np.max(B)
min_B = np.min(B)
max_idx_B = np.argmax(B)
min_idx_B = np.argmin(B)

print("A:", A)
print("B:", B)
print("Add:", add)
print("Subtract:", subtract)
print("Multiply:", multiply)
print("Divide:", divide)
print("Dot product:", dot_product)
print("Mean of A:", mean_A)
print("Median of A:", median_A)
print("Std of A:", std_A)
print("Var of A:", var_A)
print("Max of B:", max_B, "at index", max_idx_B)
print("Min of B:", min_B, "at index", min_idx_B)


A: [12 16  8 14 18]
B: [10 11 10  9 17]
Add: [22 27 18 23 35]
Subtract: [ 2  5 -2  5  1]
Multiply: [120 176  80 126 306]
Divide: [1.2        1.45454545 0.8        1.55555556 1.05882353]
Dot product: 808
Mean of A: 13.6
Median of A: 14.0
Std of A: 3.4409301068170506
Var of A: 11.84
Max of B: 17 at index 4
Min of B: 9 at index 3


In [7]:
arr = np.arange(1, 13)

reshaped_2d = arr.reshape(4, 3)
reshaped_3d = arr.reshape(2, 2, 3)
transposed_2d = reshaped_2d.T

print("2D shape:", reshaped_2d.shape)
print("3D shape:", reshaped_3d.shape)
print("Transposed shape:", transposed_2d.shape)


2D shape: (4, 3)
3D shape: (2, 2, 3)
Transposed shape: (3, 4)


In [9]:
arr = np.random.randint(10, 51, 15)

greater_than_25 = arr[arr > 25]
arr[arr < 30] = 0
divisible_by_5 = np.sum(arr % 5 == 0)

print("Original array after masking:", arr)
print("Elements > 25:", greater_than_25)
print("Count divisible by 5:", divisible_by_5)


Original array after masking: [37 38  0  0 43  0 30 43  0  0  0  0  0  0  0]
Elements > 25: [37 38 43 30 43 28]
Count divisible by 5: 11


In [11]:
linspace_arr = np.linspace(0, 1, 10)
identity_matrix = np.eye(4)
rand_arr = np.random.randint(1, 101, 20)
sorted_arr = np.sort(rand_arr)
top5 = sorted_arr[-5:]

print("Linspace 0-1:", linspace_arr)
print("Identity matrix:\n", identity_matrix)
print("Sorted array:", sorted_arr)
print("Top 5 elements:", top5)


Linspace 0-1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted array: [ 2  8  9 10 18 31 35 37 38 38 43 45 54 61 75 89 91 92 94 95]
Top 5 elements: [89 91 92 94 95]


In [13]:
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start = time.time()
product = np.dot(A, B)
end = time.time()

try:
    det = np.linalg.det(product)
    inv = np.linalg.inv(product)
except np.linalg.LinAlgError:
    det = None
    inv = None

print("Time taken:", end - start)
print("Determinant:", det)
print("Inverse exists:", inv is not None)


Time taken: 0.061316490173339844
Determinant: -7.014511450658821e+50
Inverse exists: True
